version: 2
formats: all
sphinx:
  # Path to your Sphinx configuration file.
  configuration: ./conf.py
build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
        nodejs: "18"
        rust: "1.64"
        golang: "1.19"
python:
  install:
    - requirements: requirements.txt
